/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ResultDapp } from "./ResultDapp";
export * as factories from "./factories";
export { ResultDapp__factory } from "./factories/ResultDapp__factory";
